# Autogenerated from C:/Users/Yasho/LoopHole/Polygeist/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


import sys

config.host_triple = "x86_64-w64-windows-gnu"
config.target_triple = ""
config.llvm_src_root = "C:/Users/Yasho/LoopHole/Polygeist/llvm-project/llvm"
config.llvm_obj_root = "C:/Users/Yasho/LoopHole/build"
config.llvm_tools_dir = "C:/Users/Yasho/LoopHole/build/./bin"
config.llvm_lib_dir = "C:/Users/Yasho/LoopHole/build/./lib"
config.llvm_shlib_dir = "C:/Users/Yasho/LoopHole/build/./bin"
config.llvm_shlib_ext = ".dll"
config.llvm_exe_ext = ".exe"
config.lit_tools_dir = ""
config.python_executable = ""
config.gold_executable = "C:/ProgramData/mingw64/mingw64/bin/ld.exe"
config.ld64_executable = ""
config.enable_shared = 0
config.enable_assertions = 1
config.targets_to_build = " X86"
config.native_target = "X86"
config.llvm_bindings = "".split(' ')
config.host_os = "Windows"
config.host_cc = "C:/ProgramData/mingw64/mingw64/bin/cc.exe "
config.host_cxx = "C:/ProgramData/mingw64/mingw64/bin/c++.exe "
# Note: ldflags can contain double-quoted paths, so must use single quotes here.
config.host_ldflags = ' -Wl,--stack,16777216 -Wl,--stack,16777216'
config.llvm_use_sanitizer = ""
config.llvm_host_triple = 'x86_64-w64-windows-gnu'
config.host_arch = "AMD64"
config.mlir_src_root = ""
config.mlir_obj_root = ""
config.mlir_tools_dir = ""
config.polygeist_src_root = "C:/Users/Yasho/LoopHole/Polygeist"
config.polygeist_obj_root = "C:/Users/Yasho/LoopHole/build/tools/polygeist"
config.polygeist_tools_dir = "C:/Users/Yasho/LoopHole/build/bin"
config.polygeist_shlib_dir = "C:/Users/Yasho/LoopHole/build/lib"
config.verilator_path = ""
config.polymer_enabled = "0"
config.polymer_pluto_enabled = "0"
config.polymer_isl_enabled = "0"

# Support substitution of the tools_dir with user parameters. This is
# used when we can't determine the tool dir at configuration time.
try:
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
    config.llvm_shlib_dir = config.llvm_shlib_dir % lit_config.params
except KeyError:
    e = sys.exc_info()[1]
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, "C:/Users/Yasho/LoopHole/Polygeist/test/lit.cfg.py")
