# Autogenerated from C:/Users/Yasho/LoopHole/Polygeist/llvm-project/llvm/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


import sys

config.host_triple = "x86_64-w64-windows-gnu"
config.target_triple = "x86_64-w64-windows-gnu"
config.llvm_src_root = path(r"..\..\Polygeist\llvm-project\llvm")
config.llvm_obj_root = path(r"..")
config.llvm_tools_dir = lit_config.substitute(path(r"..\bin"))
config.llvm_lib_dir = lit_config.substitute(path(r"..\lib"))
config.llvm_shlib_dir = lit_config.substitute(path(r"..\bin"))
config.llvm_shlib_ext = ".dll"
config.llvm_plugin_ext = ".dll"
config.llvm_exe_ext = ".exe"
config.lit_tools_dir = path(r"")
config.errc_messages = "No such file or directory;Is a directory;Invalid argument;Permission denied"
config.python_executable = "C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0/python3.11.exe"
config.gold_executable = "C:/ProgramData/mingw64/mingw64/bin/ld.exe"
config.ld64_executable = ""
config.osx_sysroot = path(r"")
config.ocamlfind_executable = "OCAMLFIND-NOTFOUND"
config.have_ocamlopt = 0
config.ocaml_flags = ""
config.ptxas_executable = ""
config.enable_assertions = 1
config.targets_to_build = " X86"
config.native_target = "X86"
config.llvm_bindings = "".split(' ')
config.host_os = "Windows"
config.host_cc = "C:/ProgramData/mingw64/mingw64/bin/cc.exe "
config.host_cxx = "C:/ProgramData/mingw64/mingw64/bin/c++.exe "
# Note: ldflags can contain double-quoted paths, so must use single quotes here.
config.host_ldflags = ' -Wl,--stack,16777216'
config.llvm_use_intel_jitevents = 0
config.llvm_use_sanitizer = ""
config.have_zlib = 0
config.have_zstd = 0
config.have_libxar = 0
config.have_libxml2 = 0
config.have_curl = 0
config.have_httplib = 0
config.have_dia_sdk = 0
config.enable_ffi = 0
config.build_examples = 0
config.enable_threads = 1
config.build_shared_libs = 0
config.link_llvm_dylib = 0
config.llvm_dylib_version = "18git"
config.llvm_host_triple = 'x86_64-w64-windows-gnu'
config.host_arch = "AMD64"
config.have_opt_viewer_modules = 0
config.libcxx_used = 0
config.has_plugins = 0
config.linked_bye_extension = 0
config.linked_exampleirtransforms_extension = 0
config.have_tf_aot = 0
config.have_tflite = 0
config.llvm_inliner_model_autogenerated = 0
config.llvm_raevict_model_autogenerated = 0
config.expensive_checks = 0
config.reverse_iteration = 0
config.dxil_tests = 0
config.have_llvm_driver = 0

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(
    config, os.path.join(config.llvm_src_root, "test/lit.cfg.py"))
