# Autogenerated from C:/Users/Yasho/LoopHole/Polygeist/llvm-project/lld/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


import lit.util

config.have_dia_sdk = lit.util.pythonize_bool("0")
config.llvm_src_root = path(r"..\..\..\..\Polygeist\llvm-project\llvm")
config.llvm_obj_root = path(r"..\..\..")
config.llvm_tools_dir = lit_config.substitute(path(r"..\..\..\bin"))
config.llvm_libs_dir = lit_config.substitute(path(r"..\..\..\lib"))
config.llvm_shlib_dir = path(r"..\..\..\bin")
config.llvm_shlib_ext = ".dll"
config.lit_tools_dir = path(r"")
config.enable_backtrace = 1
config.errc_messages = "No such file or directory;Is a directory;Invalid argument;Permission denied"
config.lld_obj_root = path(r"..")
config.lld_libs_dir = lit_config.substitute(path(r"..\..\..\lib"))
config.lld_tools_dir = lit_config.substitute(path(r"..\..\..\bin"))
config.host_triple = "x86_64-w64-windows-gnu"
config.target_triple = "x86_64-w64-windows-gnu"
config.python_executable = "C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0/python3.11.exe"
config.have_zlib = 0
config.have_zstd = 0
config.have_libxml2 = 0
config.sizeof_void_p = 8
config.ld_lld_default_mingw = 0
config.build_examples = 0
config.has_plugins = 0
config.linked_bye_extension = 0

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(
    config, os.path.join(path(r"..\..\..\..\Polygeist\llvm-project\lld"), "test/lit.cfg.py"))
