"""Diagram specs for the handbook (used by ``::diagram <name>`` in the sources).

Coordinates are millimetres with the origin at the top-left of the drawing.
Node: (id, x, y, w, h, "Title\\nline 2\\nline 3", kind)  kind in
input/stage/data/ext/risk/ok/warn. Edge: (from, to, label[, "dashed"]).
Group: (x, y, w, h, label) drawn as a dashed frame behind the nodes.
"""

DIAGRAMS = {
    "pipeline": {
        "size": (170, 150),
        "caption": "Figure: end-to-end data flow. Solid arrows are the main path; dashed arrows are optional or out-of-process steps.",
        "groups": [
            (2, 30, 166, 88, "packages/loophole (host Python process)"),
        ],
        "nodes": [
            ("c", 4, 4, 38, 18, "C / C++ kernel\nexamples/*.c", "input"),
            ("cg", 66, 4, 44, 18, "Polygeist cgeist\n(Docker image)\npolygeist_frontend.py", "ext"),
            ("mlir", 128, 4, 38, 18, "Affine / SCF MLIR\n(memref, affine.for)", "data"),
            ("cli", 6, 40, 34, 20, "CLI\ncli.py\nlift / batch / demo", "stage"),
            ("ex", 50, 40, 36, 20, "Stage 1: Parse\naffine_extractor.py\n-> LoopNestInfo", "stage"),
            ("tr", 96, 40, 32, 20, "Stage 2a: Rank\nsympy_tracer.py\nconfidence 0..1", "stage"),
            ("sk", 136, 40, 30, 20, "Sketch library\n35 OperationSketch\nsketch_library.py", "data"),
            ("z3", 96, 70, 32, 20, "Stage 3: Verify\nz3_checker.py\nEQUIV / REFUTED ...", "stage"),
            ("lf", 50, 70, 36, 20, "Orchestrator\nlifter.py\n-> LiftResult", "stage"),
            ("em", 50, 96, 36, 18, "Stage 4: Emit\nemitter.py\nLinalg | StableHLO", "stage"),
            ("va", 96, 96, 32, 18, "Artifact check\nmlir_validator.py", "stage"),
            ("rp", 136, 70, 30, 20, "Replay (A-14)\nreplay_checker.py", "stage"),
            ("out", 50, 126, 36, 18, "Lifted MLIR\n*_lifted.mlir", "data"),
            ("rep", 96, 126, 32, 18, "JSON report\nloophole_report.json", "data"),
            ("mo", 136, 126, 30, 18, "mlir-opt 17\n(Docker or PATH)", "ext"),
        ],
        "edges": [
            ("c", "cg", "compile / lift-c"),
            ("cg", "mlir", ""),
            ("mlir", "cli", "", "dashed"),
            ("cli", "ex", "text"),
            ("ex", "tr", ""),
            ("sk", "tr", ""),
            ("tr", "z3", "top-k"),
            ("sk", "z3", "", "dashed"),
            ("ex", "lf", ""),
            ("z3", "lf", "report"),
            ("z3", "rp", "", "dashed"),
            ("lf", "em", ""),
            ("em", "out", ""),
            ("em", "va", "", "dashed"),
            ("va", "mo", "subprocess", "dashed"),
            ("lf", "rep", "batch", "dashed"),
        ],
    },
    "module_deps": {
        "size": (170, 112),
        "caption": "Figure: import graph between modules (arrow = 'imports'). affine_extractor and sketch_library are the leaves every other layer depends on.",
        "nodes": [
            ("cli", 66, 4, 38, 14, "cli.py\n1,520 lines", "stage"),
            ("scripts", 124, 4, 44, 14, "scripts/*.py\nweekly / proof-quality", "ext"),
            ("lifter", 66, 30, 38, 14, "lifter.py\n690 lines", "stage"),
            ("pf", 4, 30, 44, 14, "polygeist_frontend.py\n446 lines", "stage"),
            ("mv", 4, 4, 44, 14, "mlir_validator.py\n247 lines", "stage"),
            ("rc", 124, 30, 44, 14, "replay_checker.py\n282 lines", "stage"),
            ("st", 10, 58, 38, 14, "sympy_tracer.py\n485 lines", "stage"),
            ("z3", 66, 58, 38, 14, "z3_checker.py\n1,736 lines", "stage"),
            ("em", 122, 58, 38, 14, "emitter.py\n1,430 lines", "stage"),
            ("ae", 40, 90, 44, 14, "affine_extractor.py\n1,301 lines", "data"),
            ("sl", 96, 90, 44, 14, "sketch_library.py\n752 lines", "data"),
            ("fx", 4, 90, 30, 14, "tests/fixtures.py\n(demo data)", "risk"),
            ("pc", 146, 90, 22, 14, "parser_corpus\n_compat.py", "stage"),
        ],
        "edges": [
            ("cli", "lifter", ""),
            ("cli", "pf", ""),
            ("cli", "mv", ""),
            ("cli", "rc", "", "dashed"),
            ("cli", "fx", "demo", "dashed"),
            ("scripts", "lifter", ""),
            ("lifter", "st", ""),
            ("lifter", "z3", ""),
            ("lifter", "em", ""),
            ("rc", "z3", ""),
            ("st", "ae", ""),
            ("z3", "ae", ""),
            ("z3", "sl", ""),
            ("em", "sl", ""),
            ("em", "ae", ""),
            ("pc", "ae", ""),
        ],
    },
    "lift_decision": {
        "size": (170, 142),
        "caption": "Figure: decision flow inside Lifter.lift() (lifter.py:363-512) and how each exit maps to a result state.",
        "nodes": [
            ("start", 60, 2, 50, 12, "lift(mlir_text)", "input"),
            ("parse", 60, 22, 50, 14, "extract()\nnever raises for most bad input", "stage"),
            ("cand", 60, 44, 50, 14, "_match_candidates()\nstructural filter + SymPy rank", "stage"),
            ("none", 124, 44, 44, 14, "no candidates\n-> REFUTED (no verdict)", "risk"),
            ("ver", 60, 66, 50, 14, "_verify_candidates()\nfirst EQUIVALENT wins", "stage"),
            ("allfail", 124, 66, 44, 14, "all ENCODE_ERROR\nverification=None", "risk"),
            ("ref", 2, 66, 48, 14, "best is NOT_EQUIVALENT\n-> error, no emission", "risk"),
            ("strict", 60, 88, 50, 14, "strict and TIMEOUT/UNKNOWN?\n-> reject", "warn"),
            ("emit", 60, 110, 50, 14, "_emit()\nEmissionError -> error", "stage"),
            ("proved", 2, 126, 48, 13, "PROVED\n(success)", "ok"),
            ("partial", 60, 128, 50, 13, "UNPROVED_TIMEOUT\n(partial_success)", "warn"),
            ("refd", 124, 100, 44, 22, "REFUTED\n(also used for 'no match'\nand 'parse failure')", "risk"),
        ],
        "edges": [
            ("start", "parse", ""),
            ("parse", "cand", ""),
            ("cand", "none", "empty"),
            ("cand", "ver", ""),
            ("ver", "allfail", "None"),
            ("ver", "ref", "refuted"),
            ("ver", "strict", ""),
            ("strict", "emit", "ok"),
            ("emit", "proved", "EQUIVALENT"),
            ("emit", "partial", "TIMEOUT"),
            ("allfail", "refd", "", "dashed"),
        ],
    },
    "verification_gap": {
        "size": (170, 96),
        "caption": "Figure: what the Z3 check really compares. Only the index expressions come from the source program; the arithmetic on the source side is re-synthesised from a coarse 'payload' guess, so arithmetic mistakes are invisible to the proof.",
        "nodes": [
            ("src", 4, 4, 50, 22, "Source loop body\nreads, arith ops (SSA dataflow),\nstore", "input"),
            ("idx", 4, 38, 50, 16, "Index expressions\n(taken from source: OK)", "ok"),
            ("ops", 4, 64, 50, 26, "Arith ops -> op-type SET\n{mulf, addf, ...}\ndataflow, operand order,\nconstants DISCARDED", "risk"),
            ("pay", 64, 64, 44, 26, "_infer_compute_payload()\nz3_checker.py:1644\ne.g. {mulf} -> COPY (bug)", "risk"),
            ("lhs", 64, 30, 44, 22, "Z3 'source' formula\nC[i,j] == f_payload(reads)", "stage"),
            ("rhs", 120, 30, 46, 22, "Z3 sketch formula\nC[i,j] == f_sketch(reads)", "stage"),
            ("sk", 120, 4, 46, 16, "OperationSketch\n(indexing maps + payload)", "data"),
            ("q", 120, 64, 46, 26, "Solver: both implications\nUNSAT => 'EQUIVALENT'\n(over mathematical reals,\nnot IEEE float)", "warn"),
        ],
        "edges": [
            ("src", "idx", ""),
            ("idx", "ops", "", "dashed"),
            ("ops", "pay", ""),
            ("idx", "lhs", ""),
            ("pay", "lhs", ""),
            ("sk", "rhs", ""),
            ("lhs", "q", ""),
            ("rhs", "q", ""),
        ],
    },
    "toolchain": {
        "size": (170, 108),
        "caption": "Figure: where each piece runs. The host only needs Python; LLVM 17, cgeist and mlir-opt live in the Docker image, which CI publishes to GHCR.",
        "groups": [
            (2, 2, 70, 58, "Developer host (Windows / Linux)"),
            (84, 2, 84, 58, "Docker image loophole-polygeist:llvm17"),
            (2, 70, 166, 36, "GitHub"),
        ],
        "nodes": [
            ("venv", 8, 12, 58, 16, "Python venv\npip install -e packages/loophole", "stage"),
            ("clih", 8, 36, 58, 16, "loophole CLI\ncompile / lift / batch", "stage"),
            ("cg", 90, 12, 34, 16, "cgeist / cgeist++\n(built from source)", "ext"),
            ("llvm", 130, 12, 34, 16, "apt LLVM/MLIR 17\nclang-17, mlir-opt", "ext"),
            ("patch", 90, 36, 74, 16, "Dockerfile string patches to Polygeist\n(llvm17bump branch, GPU passes removed)", "risk"),
            ("ci", 8, 80, 48, 20, "ci.yml\npytest + apt mlir-opt\n(ubuntu-latest, py3.11)", "stage"),
            ("pub", 64, 80, 48, 20, "publish-docker-image.yml\non docker/** change", "stage"),
            ("ghcr", 120, 80, 44, 20, "GHCR (private)\nghcr.io/schizoid-man/\nloophole-polygeist", "data"),
        ],
        "edges": [
            ("venv", "clih", ""),
            ("clih", "cg", "docker run -v", "dashed"),
            ("clih", "llvm", "", "dashed"),
            ("pub", "ghcr", "push"),
            ("ghcr", "clih", "docker pull", "dashed"),
        ],
    },
    "phases": {
        "size": (170, 42),
        "caption": "Figure: remediation phases. Phase 0 is a precondition for trusting any number the tool prints.",
        "nodes": [
            ("p0", 2, 4, 38, 34, "Phase 0 (week 1-2)\nStop the bleeding\n- CI green\n- flag false proofs\n- honest docs", "risk"),
            ("p1", 45, 4, 38, 34, "Phase 1 (week 2-6)\nSound verifier\n- dataflow encoding\n- steps, IV roles\n- real verifier", "warn"),
            ("p2", 88, 4, 38, 34, "Phase 2 (week 6-10)\nValid artifacts\n- emitter syntax\n- stablehlo-opt\n- numeric oracle", "stage"),
            ("p3", 131, 4, 37, 34, "Phase 3 (ongoing)\nMaintainability\n- dedupe, split cli\n- typed config\n- docs as code", "ok"),
        ],
        "edges": [
            ("p0", "p1", ""),
            ("p1", "p2", ""),
            ("p2", "p3", ""),
        ],
    },
}
