"""
emitter.py — MLIR text emitter for Linalg and StableHLO dialects.

Produces syntactically valid MLIR text (textual IR format) that can be
piped directly to `mlir-opt` for further compilation or verification.

Each emitter function accepts:
  - A matched OperationSketch
  - Concrete tensor shapes extracted from the source loop
  - The element type (f32, f64, etc.)
  - The function name (from the source)

And produces a complete `func.func` MLIR module as a string.

The emitter supports:
  Linalg named ops: linalg.matmul, linalg.transpose, linalg.conv_*,
                    linalg.dot, linalg.matvec, linalg.fill, etc.
  Linalg generic:   linalg.generic with fully-specified affine maps
  StableHLO:        stablehlo.dot_general, stablehlo.convolution,
                    stablehlo.reduce, stablehlo.map
"""

from __future__ import annotations

from typing import Dict, List, Optional, Tuple
from loophole.affine_extractor import LoopNestInfo
from loophole.sketch_library import ComputePayloadType, OperationSketch


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _memref_type(shape: List[int], elem: str) -> str:
    dims = "x".join(str(d) if d > 0 else "?" for d in shape)
    return f"memref<{dims}x{elem}>"


def _tensor_type(shape: List[int], elem: str) -> str:
    dims = "x".join(str(d) if d > 0 else "?" for d in shape)
    return f"tensor<{dims}x{elem}>"


def _indent(text: str, n: int = 2) -> str:
    pad = " " * n
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


def _emit_module_header() -> str:
    return 'module {\n'


def _emit_module_footer() -> str:
    return '}\n'


def _map_elem_type(etype: str) -> str:
    """Normalise element type string."""
    mapping = {
        'float': 'f32', 'double': 'f64',
        'int': 'i32', 'long': 'i64',
    }
    return mapping.get(etype, etype)


# ---------------------------------------------------------------------------
# Linalg Emitter
# ---------------------------------------------------------------------------

class LinalgEmitter:
    """
    Emits MLIR Linalg dialect code for a matched sketch.

    Preferred order:
      1. Named Linalg operation (e.g., linalg.matmul) when available.
      2. linalg.generic with fully-specified affine maps as fallback.
    """

    # Map of sketch name → emit method name
    _NAMED_OP_HANDLERS = {
        "linalg.matmul":               "_emit_matmul",
        "linalg.transpose":            "_emit_transpose",
        "linalg.dot":                  "_emit_dot",
        "linalg.matvec":               "_emit_matvec",
        "linalg.vecmat":               "_emit_vecmat",
        "linalg.batch_matmul":         "_emit_batch_matmul",
        "linalg.conv_1d_ncw_fcw":      "_emit_conv1d_ncw",
        "linalg.conv_1d_nwc_wcf":      "_emit_conv1d_nwc",
        "linalg.conv_2d":              "_emit_conv2d_simple",
        "linalg.conv_2d_nhwc_hwcf":    "_emit_conv2d_nhwc",
        "linalg.conv_2d_nchw_fchw":    "_emit_conv2d_nchw",
        "linalg.pooling_nhwc_max":     "_emit_pool2d_max",
        "linalg.copy":                 "_emit_copy",
        "linalg.map{arith.addf}":      "_emit_elementwise",
        "linalg.map{arith.addf}_1d":   "_emit_elementwise",
        "linalg.map{arith.mulf}":      "_emit_elementwise",
        "linalg.map{arith.subf}":      "_emit_elementwise",
        "linalg.map{arith.maxf_zero}": "_emit_relu",
        "linalg.map{arith.mulf_scalar}": "_emit_scale",
        "linalg.reduce{arith.addf}_rowsum": "_emit_reduce_sum",
        "linalg.reduce{arith.addf}_colsum": "_emit_reduce_sum",
        "linalg.reduce{arith.maxf}":   "_emit_reduce_max",
    }

    def emit(
        self,
        sketch: OperationSketch,
        loop: LoopNestInfo,
        func_name: Optional[str] = None,
    ) -> str:
        """
        Emit a complete MLIR module containing the lifted function.
        Returns the MLIR text as a string.
        """
        name = func_name or f"lifted_{loop.func_name}"
        handler_method = self._NAMED_OP_HANDLERS.get(sketch.name)
        if handler_method and hasattr(self, handler_method):
            func_body = getattr(self, handler_method)(sketch, loop, name)
        else:
            func_body = self._emit_generic(sketch, loop, name)

        lines = [
            "// LoopHole: Automatically lifted from scalar loop nest",
            f"// Source: {loop.func_name} → {sketch.name}",
            f"// Description: {sketch.description}",
            "// Generated by LoopHole POC v0.1.0",
            "",
        ]
        lines.append(_emit_module_header())
        lines.append(func_body)
        lines.append(_emit_module_footer())
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # BLAS ops
    # ------------------------------------------------------------------

    def _emit_matmul(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%C'

        A_name = input_tensors[0] if len(input_tensors) > 0 else '%A'
        B_name = input_tensors[1] if len(input_tensors) > 1 else '%B'
        A_shape = shapes.get(A_name, [4, 4])
        B_shape = shapes.get(B_name, [4, 4])
        C_shape = shapes.get(out, [A_shape[0], B_shape[1]])

        A_type = _memref_type(A_shape, et)
        B_type = _memref_type(B_shape, et)
        C_type = _memref_type(C_shape, et)

        return (
            f"  func.func @{name}(%A: {A_type}, %B: {B_type}, %C: {C_type}) {{\n"
            f"    linalg.matmul\n"
            f"      ins(%A, %B : {A_type}, {B_type})\n"
            f"      outs(%C : {C_type})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_transpose(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%B'

        A_name = input_tensors[0] if input_tensors else '%A'
        A_shape = shapes.get(A_name, [4, 4])
        B_shape = shapes.get(out, [A_shape[1], A_shape[0]])

        A_type = _memref_type(A_shape, et)
        B_type = _memref_type(B_shape, et)

        # Infer permutation from access pattern
        perm = self._infer_transpose_perm(loop, len(A_shape))
        perm_str = "[" + ", ".join(str(p) for p in perm) + "]"

        return (
            f"  func.func @{name}(%A: {A_type}, %B: {B_type}) {{\n"
            f"    linalg.transpose\n"
            f"      ins(%A : {A_type})\n"
            f"      outs(%B : {B_type})\n"
            f"      permutation = {perm_str}\n"
            f"    return\n"
            f"  }}"
        )

    def _infer_transpose_perm(self, loop: LoopNestInfo, rank: int) -> List[int]:
        """Infer the transposition permutation from access patterns."""
        if loop.writes:
            w = loop.writes[0]
            # The output indices tell us how the indices are permuted
            # e.g., ['j', 'i'] for a 2D transpose → perm [1, 0]
            all_ivs = loop.induction_vars
            perm = []
            for expr in w.index_exprs:
                for i, iv in enumerate(all_ivs):
                    if iv in expr:
                        perm.append(i)
                        break
            if len(perm) == rank:
                return perm
        return list(range(rank - 1, -1, -1))  # default: reverse all dims

    def _emit_dot(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%c'

        A_name = input_tensors[0] if len(input_tensors) > 0 else '%A'
        B_name = input_tensors[1] if len(input_tensors) > 1 else '%B'
        A_shape = shapes.get(A_name, [16])
        B_shape = shapes.get(B_name, [16])
        C_shape = shapes.get(out, [])

        A_type = _memref_type(A_shape, et)
        B_type = _memref_type(B_shape, et)
        C_type = _memref_type(C_shape if C_shape else [1], et)

        return (
            f"  func.func @{name}(%A: {A_type}, %B: {B_type}, %c: {C_type}) {{\n"
            f"    linalg.dot\n"
            f"      ins(%A, %B : {A_type}, {B_type})\n"
            f"      outs(%c : {C_type})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_matvec(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%y'

        A_name = input_tensors[0] if len(input_tensors) > 0 else '%A'
        x_name = input_tensors[1] if len(input_tensors) > 1 else '%x'
        A_shape = shapes.get(A_name, [8, 8])
        x_shape = shapes.get(x_name, [A_shape[1]])
        y_shape = shapes.get(out, [A_shape[0]])

        A_type = _memref_type(A_shape, et)
        x_type = _memref_type(x_shape, et)
        y_type = _memref_type(y_shape, et)

        return (
            f"  func.func @{name}(%A: {A_type}, %x: {x_type}, %y: {y_type}) {{\n"
            f"    linalg.matvec\n"
            f"      ins(%A, %x : {A_type}, {x_type})\n"
            f"      outs(%y : {y_type})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_vecmat(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%y'

        x_name = input_tensors[0] if len(input_tensors) > 0 else '%x'
        A_name = input_tensors[1] if len(input_tensors) > 1 else '%A'
        x_shape = shapes.get(x_name, [8])
        A_shape = shapes.get(A_name, [8, 8])
        y_shape = shapes.get(out, [A_shape[1]])

        x_type = _memref_type(x_shape, et)
        A_type = _memref_type(A_shape, et)
        y_type = _memref_type(y_shape, et)

        return (
            f"  func.func @{name}(%x: {x_type}, %A: {A_type}, %y: {y_type}) {{\n"
            f"    linalg.vecmat\n"
            f"      ins(%x, %A : {x_type}, {A_type})\n"
            f"      outs(%y : {y_type})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_batch_matmul(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%C'

        A_name = input_tensors[0] if len(input_tensors) > 0 else '%A'
        B_name = input_tensors[1] if len(input_tensors) > 1 else '%B'
        A_shape = shapes.get(A_name, [2, 4, 4])
        B_shape = shapes.get(B_name, [2, 4, 4])
        C_shape = shapes.get(out, [A_shape[0], A_shape[1], B_shape[2]])

        A_type = _memref_type(A_shape, et)
        B_type = _memref_type(B_shape, et)
        C_type = _memref_type(C_shape, et)

        return (
            f"  func.func @{name}(%A: {A_type}, %B: {B_type}, %C: {C_type}) {{\n"
            f"    linalg.batch_matmul\n"
            f"      ins(%A, %B : {A_type}, {B_type})\n"
            f"      outs(%C : {C_type})\n"
            f"    return\n"
            f"  }}"
        )

    # ------------------------------------------------------------------
    # Convolution ops
    # ------------------------------------------------------------------

    def _emit_conv1d_ncw(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%O'

        I_name = input_tensors[0] if len(input_tensors) > 0 else '%I'
        K_name = input_tensors[1] if len(input_tensors) > 1 else '%K'

        # Infer shapes from bounds
        ivs = loop.induction_vars
        bounds = loop.bounds
        N = _bound_size(bounds, loop.parallel_vars, 0)
        W_out = _bound_size(bounds, loop.parallel_vars, 1)
        KW = _bound_size(bounds, loop.reduction_vars, 0)
        W_in = W_out + KW - 1

        I_shape = shapes.get(I_name, [N, W_in])
        K_shape = shapes.get(K_name, [KW])
        O_shape = shapes.get(out, [N, W_out])

        I_type = _memref_type(I_shape, et)
        K_type = _memref_type(K_shape, et)
        O_type = _memref_type(O_shape, et)

        return (
            f"  func.func @{name}(%I: {I_type}, %K: {K_type}, %O: {O_type}) {{\n"
            f"    linalg.conv_1d_ncw_fcw\n"
            f"      {{dilations = dense<1> : tensor<1xi64>,\n"
            f"       strides   = dense<1> : tensor<1xi64>}}\n"
            f"      ins(%I, %K : {I_type}, {K_type})\n"
            f"      outs(%O : {O_type})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_conv1d_nwc(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%O'

        I_name = input_tensors[0] if len(input_tensors) > 0 else '%I'
        K_name = input_tensors[1] if len(input_tensors) > 1 else '%K'
        bounds = loop.bounds
        par = loop.parallel_vars
        red = loop.reduction_vars

        N = _bound_size(bounds, par, 0)
        Wout = _bound_size(bounds, par, 1)
        F = _bound_size(bounds, par, 2) if len(par) > 2 else 1
        KW = _bound_size(bounds, red, 0)
        C = _bound_size(bounds, red, 1) if len(red) > 1 else 1
        Win = Wout + KW - 1

        I_shape = shapes.get(I_name, [N, Win, C])
        K_shape = shapes.get(K_name, [KW, C, F])
        O_shape = shapes.get(out, [N, Wout, F])

        I_type = _memref_type(I_shape, et)
        K_type = _memref_type(K_shape, et)
        O_type = _memref_type(O_shape, et)

        return (
            f"  func.func @{name}(%I: {I_type}, %K: {K_type}, %O: {O_type}) {{\n"
            f"    linalg.conv_1d_nwc_wcf\n"
            f"      {{dilations = dense<1> : tensor<1xi64>,\n"
            f"       strides   = dense<1> : tensor<1xi64>}}\n"
            f"      ins(%I, %K : {I_type}, {K_type})\n"
            f"      outs(%O : {O_type})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_conv2d_simple(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%O'

        I_name = input_tensors[0] if len(input_tensors) > 0 else '%I'
        K_name = input_tensors[1] if len(input_tensors) > 1 else '%K'
        bounds = loop.bounds
        par = loop.parallel_vars
        red = loop.reduction_vars

        OH = _bound_size(bounds, par, 0)
        OW = _bound_size(bounds, par, 1)
        KH = _bound_size(bounds, red, 0)
        KW = _bound_size(bounds, red, 1) if len(red) > 1 else KH
        IH = OH + KH - 1
        IW = OW + KW - 1

        I_shape = shapes.get(I_name, [IH, IW])
        K_shape = shapes.get(K_name, [KH, KW])
        O_shape = shapes.get(out, [OH, OW])

        I_type = _memref_type(I_shape, et)
        K_type = _memref_type(K_shape, et)
        O_type = _memref_type(O_shape, et)

        return (
            f"  func.func @{name}(%I: {I_type}, %K: {K_type}, %O: {O_type}) {{\n"
            f"    linalg.conv_2d\n"
            f"      {{dilations = dense<1> : tensor<2xi64>,\n"
            f"       strides   = dense<1> : tensor<2xi64>}}\n"
            f"      ins(%I, %K : {I_type}, {K_type})\n"
            f"      outs(%O : {O_type})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_conv2d_nhwc(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%O'

        I_name = input_tensors[0] if len(input_tensors) > 0 else '%I'
        K_name = input_tensors[1] if len(input_tensors) > 1 else '%K'
        bounds = loop.bounds
        par = loop.parallel_vars
        red = loop.reduction_vars

        N  = _bound_size(bounds, par, 0)
        OH = _bound_size(bounds, par, 1)
        OW = _bound_size(bounds, par, 2)
        OC = _bound_size(bounds, par, 3) if len(par) > 3 else 1
        KH = _bound_size(bounds, red, 0)
        KW = _bound_size(bounds, red, 1) if len(red) > 1 else KH
        IC = _bound_size(bounds, red, 2) if len(red) > 2 else 1
        IH = OH + KH - 1
        IW = OW + KW - 1

        I_shape = shapes.get(I_name, [N, IH, IW, IC])
        K_shape = shapes.get(K_name, [KH, KW, IC, OC])
        O_shape = shapes.get(out, [N, OH, OW, OC])

        I_type = _memref_type(I_shape, et)
        K_type = _memref_type(K_shape, et)
        O_type = _memref_type(O_shape, et)

        return (
            f"  func.func @{name}(%I: {I_type}, %K: {K_type}, %O: {O_type}) {{\n"
            f"    linalg.conv_2d_nhwc_hwcf\n"
            f"      {{dilations = dense<1> : tensor<2xi64>,\n"
            f"       strides   = dense<1> : tensor<2xi64>}}\n"
            f"      ins(%I, %K : {I_type}, {K_type})\n"
            f"      outs(%O : {O_type})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_conv2d_nchw(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%O'

        I_name = input_tensors[0] if len(input_tensors) > 0 else '%I'
        K_name = input_tensors[1] if len(input_tensors) > 1 else '%K'
        bounds = loop.bounds
        par = loop.parallel_vars
        red = loop.reduction_vars

        N  = _bound_size(bounds, par, 0)
        OC = _bound_size(bounds, par, 1)
        OH = _bound_size(bounds, par, 2)
        OW = _bound_size(bounds, par, 3) if len(par) > 3 else 1
        IC = _bound_size(bounds, red, 0)
        KH = _bound_size(bounds, red, 1) if len(red) > 1 else 3
        KW = _bound_size(bounds, red, 2) if len(red) > 2 else 3
        IH = OH + KH - 1
        IW = OW + KW - 1

        I_shape = shapes.get(I_name, [N, IC, IH, IW])
        K_shape = shapes.get(K_name, [OC, IC, KH, KW])
        O_shape = shapes.get(out, [N, OC, OH, OW])

        I_type = _memref_type(I_shape, et)
        K_type = _memref_type(K_shape, et)
        O_type = _memref_type(O_shape, et)

        return (
            f"  func.func @{name}(%I: {I_type}, %K: {K_type}, %O: {O_type}) {{\n"
            f"    linalg.conv_2d_nchw_fchw\n"
            f"      {{dilations = dense<1> : tensor<2xi64>,\n"
            f"       strides   = dense<1> : tensor<2xi64>}}\n"
            f"      ins(%I, %K : {I_type}, {K_type})\n"
            f"      outs(%O : {O_type})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_pool2d_max(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%O'

        I_name = input_tensors[0] if input_tensors else '%I'
        bounds = loop.bounds
        par = loop.parallel_vars
        red = loop.reduction_vars

        N  = _bound_size(bounds, par, 0)
        OH = _bound_size(bounds, par, 1)
        OW = _bound_size(bounds, par, 2)
        C  = _bound_size(bounds, par, 3) if len(par) > 3 else 1
        KH = _bound_size(bounds, red, 0)
        KW = _bound_size(bounds, red, 1) if len(red) > 1 else KH
        IH, IW = OH + KH - 1, OW + KW - 1

        I_shape = shapes.get(I_name, [N, IH, IW, C])
        W_shape = [KH, KW]
        O_shape = shapes.get(out, [N, OH, OW, C])

        I_type = _memref_type(I_shape, et)
        W_type = _memref_type(W_shape, et)
        O_type = _memref_type(O_shape, et)

        return (
            f"  func.func @{name}(%I: {I_type}, %W: {W_type}, %O: {O_type}) {{\n"
            f"    linalg.pooling_nhwc_max\n"
            f"      {{dilations = dense<1> : tensor<2xi64>,\n"
            f"       strides   = dense<1> : tensor<2xi64>}}\n"
            f"      ins(%I, %W : {I_type}, {W_type})\n"
            f"      outs(%O : {O_type})\n"
            f"    return\n"
            f"  }}"
        )

    # ------------------------------------------------------------------
    # Elementwise and reduction ops
    # ------------------------------------------------------------------

    def _emit_elementwise(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        """Emit linalg.map for elementwise binary operations."""
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%C'

        A_name = input_tensors[0] if len(input_tensors) > 0 else '%A'
        B_name = input_tensors[1] if len(input_tensors) > 1 else '%B'

        A_shape = shapes.get(A_name, [8, 8])
        B_shape = shapes.get(B_name, [8, 8])
        C_shape = shapes.get(out, A_shape)

        A_type = _memref_type(A_shape, et)
        B_type = _memref_type(B_shape, et)
        C_type = _memref_type(C_shape, et)

        # Infer arith op from sketch name
        arith_op = "addf"
        if "mulf" in sketch.name:
            arith_op = "mulf"
        elif "subf" in sketch.name:
            arith_op = "subf"

        return (
            f"  func.func @{name}(%A: {A_type}, %B: {B_type}, %C: {C_type}) {{\n"
            f"    linalg.map\n"
            f"      ins(%A, %B : {A_type}, {B_type})\n"
            f"      outs(%C : {C_type})\n"
            f"      ({{%a: {et}, %b: {et}}} -> {{\n"
            f"        %res = arith.{arith_op} %a, %b : {et}\n"
            f"        linalg.yield %res : {et}\n"
            f"      }})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_relu(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%B'

        A_name = input_tensors[0] if input_tensors else '%A'
        A_shape = shapes.get(A_name, [8, 8])
        B_shape = shapes.get(out, A_shape)

        A_type = _memref_type(A_shape, et)
        B_type = _memref_type(B_shape, et)

        return (
            f"  func.func @{name}(%A: {A_type}, %B: {B_type}) {{\n"
            f"    %zero = arith.constant 0.0 : {et}\n"
            f"    linalg.map\n"
            f"      ins(%A : {A_type})\n"
            f"      outs(%B : {B_type})\n"
            f"      ({{%a: {et}}} -> {{\n"
            f"        %res = arith.maxf %a, %zero : {et}\n"
            f"        linalg.yield %res : {et}\n"
            f"      }})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_scale(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%B'

        A_name = input_tensors[0] if input_tensors else '%A'
        A_shape = shapes.get(A_name, [8, 8])
        B_shape = shapes.get(out, A_shape)

        A_type = _memref_type(A_shape, et)
        B_type = _memref_type(B_shape, et)

        return (
            f"  func.func @{name}(%A: {A_type}, %alpha: {et}, %B: {B_type}) {{\n"
            f"    linalg.map\n"
            f"      ins(%A : {A_type})\n"
            f"      outs(%B : {B_type})\n"
            f"      ({{%a: {et}}} -> {{\n"
            f"        %res = arith.mulf %a, %alpha : {et}\n"
            f"        linalg.yield %res : {et}\n"
            f"      }})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_copy(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%B'

        A_name = input_tensors[0] if input_tensors else '%A'
        A_shape = shapes.get(A_name, [8, 8])
        B_shape = shapes.get(out, A_shape)

        A_type = _memref_type(A_shape, et)
        B_type = _memref_type(B_shape, et)

        return (
            f"  func.func @{name}(%A: {A_type}, %B: {B_type}) {{\n"
            f"    linalg.copy\n"
            f"      ins(%A : {A_type})\n"
            f"      outs(%B : {B_type})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_reduce_sum(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%B'

        A_name = input_tensors[0] if input_tensors else '%A'
        A_shape = shapes.get(A_name, [8, 8])

        # Determine reduction dimension
        red_dim = 1 if "rowsum" in sketch.name else 0
        B_shape = shapes.get(out, [A_shape[1 - red_dim]] if len(A_shape) > 1 else [1])

        A_type = _memref_type(A_shape, et)
        B_type = _memref_type(B_shape, et)

        return (
            f"  func.func @{name}(%A: {A_type}, %B: {B_type}) {{\n"
            f"    linalg.reduce\n"
            f"      ins(%A : {A_type})\n"
            f"      outs(%B : {B_type})\n"
            f"      dimensions = [{red_dim}]\n"
            f"      ({{%a: {et}, %b: {et}}} -> {{\n"
            f"        %sum = arith.addf %a, %b : {et}\n"
            f"        linalg.yield %sum : {et}\n"
            f"      }})\n"
            f"    return\n"
            f"  }}"
        )

    def _emit_reduce_max(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%B'

        A_name = input_tensors[0] if input_tensors else '%A'
        A_shape = shapes.get(A_name, [8, 8])
        B_shape = shapes.get(out, [A_shape[0]])

        A_type = _memref_type(A_shape, et)
        B_type = _memref_type(B_shape, et)

        return (
            f"  func.func @{name}(%A: {A_type}, %B: {B_type}) {{\n"
            f"    linalg.reduce\n"
            f"      ins(%A : {A_type})\n"
            f"      outs(%B : {B_type})\n"
            f"      dimensions = [1]\n"
            f"      ({{%a: {et}, %b: {et}}} -> {{\n"
            f"        %res = arith.maxf %a, %b : {et}\n"
            f"        linalg.yield %res : {et}\n"
            f"      }})\n"
            f"    return\n"
            f"  }}"
        )

    # ------------------------------------------------------------------
    # Generic fallback: linalg.generic
    # ------------------------------------------------------------------

    def _emit_generic(self, sketch: OperationSketch, loop: LoopNestInfo, name: str) -> str:
        """Emit a fully-specified linalg.generic for any operation."""
        et = _map_elem_type(loop.element_type)
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%C'

        # Build affine map attributes
        map_attrs = []
        for i, map_str in enumerate(sketch.indexing_maps):
            # Convert "(m, n, k) -> (m, k)" to MLIR affine_map<(m,n,k) -> (m,k)>
            clean = map_str.replace(' ', '')
            map_attrs.append(f"    #map{i} = affine_map<{clean}>")

        maps_block = "\n".join(map_attrs)

        # Build iterator types
        it_str = ", ".join(f'"{t.value}"' for t in sketch.iterator_types)

        # Build operand types
        operand_types = []
        for i, t_name in enumerate(input_tensors[:sketch.num_inputs]):
            shape = shapes.get(t_name, [4, 4])
            operand_types.append(_memref_type(shape, et))
        out_shape = shapes.get(out, [4, 4])
        out_type = _memref_type(out_shape, et)

        ins_parts = [f"%in{i}: {t}" for i, t in enumerate(operand_types)]
        ins_decl = ", ".join(f"%in{i}" for i in range(len(operand_types)))
        ins_types = ", ".join(operand_types)

        # Build compute body
        body_str = self._build_generic_body(sketch, et)

        # Build block args
        block_args_in = ", ".join(f"%a{i}: {et}" for i in range(sketch.num_inputs))
        block_args = f"{block_args_in}, %out: {et}"

        func_args = ", ".join(
            f"%in{i}: {t}" for i, t in enumerate(operand_types)
        ) + f", %out_buf: {out_type}"

        map_refs = "[" + ", ".join(f"#map{i}" for i in range(len(sketch.indexing_maps))) + "]"

        return (
            f"{maps_block}\n"
            f"  func.func @{name}({func_args}) {{\n"
            f"    linalg.generic {{\n"
            f"      indexing_maps = {map_refs},\n"
            f"      iterator_types = [{it_str}]\n"
            f"    }}\n"
            f"    ins({ins_decl} : {ins_types})\n"
            f"    outs(%out_buf : {out_type}) {{\n"
            f"    ^bb0({block_args}):\n"
            f"      {body_str}\n"
            f"    }}\n"
            f"    return\n"
            f"  }}"
        )

    def _build_generic_body(self, sketch: OperationSketch, et: str) -> str:
        """Build the linalg.generic body block."""
        cp = sketch.compute_payload
        if cp == ComputePayloadType.MULTIPLY_ACCUMULATE:
            return (
                f"%mul = arith.mulf %a0, %a1 : {et}\n"
                f"      %add = arith.addf %out, %mul : {et}\n"
                f"      linalg.yield %add : {et}"
            )
        elif cp == ComputePayloadType.ADD:
            return f"%res = arith.addf %a0, %a1 : {et}\n      linalg.yield %res : {et}"
        elif cp == ComputePayloadType.SUBTRACT:
            return f"%res = arith.subf %a0, %a1 : {et}\n      linalg.yield %res : {et}"
        elif cp == ComputePayloadType.MULTIPLY:
            return f"%res = arith.mulf %a0, %a1 : {et}\n      linalg.yield %res : {et}"
        elif cp == ComputePayloadType.COPY:
            return f"linalg.yield %a0 : {et}"
        elif cp == ComputePayloadType.ACCUMULATE_ADD:
            return f"%res = arith.addf %a0, %out : {et}\n      linalg.yield %res : {et}"
        elif cp == ComputePayloadType.ACCUMULATE_MAX:
            return f"%res = arith.maxf %a0, %out : {et}\n      linalg.yield %res : {et}"
        elif cp == ComputePayloadType.RELU:
            return (
                f"%zero = arith.constant 0.0 : {et}\n"
                f"      %res = arith.maxf %a0, %zero : {et}\n"
                f"      linalg.yield %res : {et}"
            )
        elif cp == ComputePayloadType.NEGATE:
            return f"%res = arith.negf %a0 : {et}\n      linalg.yield %res : {et}"
        else:
            return f"linalg.yield %a0 : {et}"


# ---------------------------------------------------------------------------
# StableHLO Emitter
# ---------------------------------------------------------------------------

class StableHLOEmitter:
    """Emits MLIR StableHLO dialect code for matched sketches."""

    def emit(
        self,
        sketch: OperationSketch,
        loop: LoopNestInfo,
        func_name: Optional[str] = None,
    ) -> str:
        name = func_name or f"lifted_{loop.func_name}"
        et = _map_elem_type(loop.element_type)

        if "dot_general" in sketch.name or sketch.name == "stablehlo.dot_general":
            body = self._emit_dot_general(sketch, loop, name, et)
        elif "convolution" in sketch.name:
            body = self._emit_convolution(sketch, loop, name, et)
        elif "reduce" in sketch.name:
            body = self._emit_reduce(sketch, loop, name, et)
        else:
            body = self._emit_dot_general(sketch, loop, name, et)

        lines = [
            "// LoopHole: Automatically lifted from scalar loop nest (StableHLO target)",
            f"// Source: {loop.func_name} → {sketch.name}",
            f"// Description: {sketch.description}",
            "",
        ]
        lines.append(_emit_module_header())
        lines.append(body)
        lines.append(_emit_module_footer())
        return "\n".join(lines)

    def _emit_dot_general(
        self, sketch: OperationSketch, loop: LoopNestInfo, name: str, et: str
    ) -> str:
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%C'

        A_name = input_tensors[0] if len(input_tensors) > 0 else '%A'
        B_name = input_tensors[1] if len(input_tensors) > 1 else '%B'
        A_shape = shapes.get(A_name, [4, 4])
        B_shape = shapes.get(B_name, [4, 4])
        C_shape = [A_shape[0], B_shape[1]] if len(B_shape) > 1 else [A_shape[0], 1]

        A_type = _tensor_type(A_shape, et)
        B_type = _tensor_type(B_shape, et)
        C_type = _tensor_type(C_shape, et)

        return (
            f"  func.func @{name}(%A: {A_type}, %B: {B_type}) -> {C_type} {{\n"
            f"    %result = stablehlo.dot_general %A, %B,\n"
            f"      contracting_dims = [1] x [0]\n"
            f"      : ({A_type}, {B_type}) -> {C_type}\n"
            f"    return %result : {C_type}\n"
            f"  }}"
        )

    def _emit_convolution(
        self, sketch: OperationSketch, loop: LoopNestInfo, name: str, et: str
    ) -> str:
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%O'

        I_name = input_tensors[0] if len(input_tensors) > 0 else '%I'
        K_name = input_tensors[1] if len(input_tensors) > 1 else '%K'
        bounds = loop.bounds
        par = loop.parallel_vars
        red = loop.reduction_vars

        N = _bound_size(bounds, par, 0)
        OH = _bound_size(bounds, par, 1)
        OW = _bound_size(bounds, par, 2)
        OC = _bound_size(bounds, par, 3) if len(par) > 3 else 1
        KH = _bound_size(bounds, red, 0)
        KW = _bound_size(bounds, red, 1) if len(red) > 1 else KH
        IC = _bound_size(bounds, red, 2) if len(red) > 2 else 1
        IH, IW = OH + KH - 1, OW + KW - 1

        I_shape = shapes.get(I_name, [N, IH, IW, IC])
        K_shape = shapes.get(K_name, [KH, KW, IC, OC])
        O_shape = shapes.get(out, [N, OH, OW, OC])

        I_type = _tensor_type(I_shape, et)
        K_type = _tensor_type(K_shape, et)
        O_type = _tensor_type(O_shape, et)

        return (
            f"  func.func @{name}(%I: {I_type}, %K: {K_type}) -> {O_type} {{\n"
            f"    %result = stablehlo.convolution(%I, %K)\n"
            f"      dim_numbers = [b, 0, 1, f]x[0, 1, i, o]->[b, 0, 1, f],\n"
            f"      window = {{stride = [1, 1], pad = [[0, 0], [0, 0]],\n"
            f"                lhs_dilate = [1, 1], rhs_dilate = [1, 1]}}\n"
            f"      : ({I_type}, {K_type}) -> {O_type}\n"
            f"    return %result : {O_type}\n"
            f"  }}"
        )

    def _emit_reduce(
        self, sketch: OperationSketch, loop: LoopNestInfo, name: str, et: str
    ) -> str:
        shapes = loop.tensor_shapes
        input_tensors = loop.input_tensors
        out = loop.output_tensor or '%B'

        A_name = input_tensors[0] if input_tensors else '%A'
        A_shape = shapes.get(A_name, [4, 4])
        B_shape = shapes.get(out, [A_shape[0]])

        A_type = _tensor_type(A_shape, et)
        B_type = _tensor_type(B_shape, et)
        init_type = _tensor_type([], et) if not B_shape else _tensor_type(B_shape, et)

        return (
            f"  func.func @{name}(%A: {A_type}) -> {B_type} {{\n"
            f"    %init = stablehlo.constant dense<0.0> : tensor<{et}>\n"
            f"    %result = stablehlo.reduce(%A init: %init) applies stablehlo.add\n"
            f"      across dimensions = [1]\n"
            f"      : ({A_type}, tensor<{et}>) -> {B_type}\n"
            f"    return %result : {B_type}\n"
            f"  }}"
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _bound_size(
    bounds: Dict[str, Tuple],
    iv_list: List[str],
    idx: int,
) -> int:
    """Get the size (hi - lo) for the iv at position idx in iv_list."""
    if idx >= len(iv_list):
        return 1
    iv = iv_list[idx]
    lo, hi = bounds.get(iv, (0, 1))
    lo_int = lo if isinstance(lo, int) else 0
    hi_int = hi if isinstance(hi, int) else 1
    return max(1, hi_int - lo_int)
