# Autogenerated from C:/Users/Yasho/LoopHole/Polygeist/llvm-project/mlir/test/Unit/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


import sys

config.llvm_tools_dir = lit_config.substitute("C:/Users/Yasho/LoopHole/build/./bin")
config.llvm_build_mode = lit_config.substitute(".")
config.mlir_obj_root = "C:/Users/Yasho/LoopHole/build/tools/mlir"

# Let the main config do the real work.
lit_config.load_config(config, "C:/Users/Yasho/LoopHole/Polygeist/llvm-project/mlir/test/Unit/lit.cfg.py")
