# Autogenerated from C:/Users/Yasho/LoopHole/Polygeist/llvm-project/mlir/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


import sys

config.target_triple = "x86_64-w64-windows-gnu"
config.llvm_tools_dir = lit_config.substitute("C:/Users/Yasho/LoopHole/build/./bin")
config.llvm_shlib_ext = ".dll"
config.llvm_shlib_dir = lit_config.substitute(path(r"C:/Users/Yasho/LoopHole/build/./bin"))
config.python_executable = "C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0/python3.11.exe"
config.enable_assertions = 1
config.native_target = "X86"
config.host_os = "Windows"
config.host_cc = "C:/ProgramData/mingw64/mingw64/bin/cc.exe "
config.host_cxx = "C:/ProgramData/mingw64/mingw64/bin/c++.exe "
config.enable_libcxx = "OFF"
config.host_cmake = "C:/Program Files/CMake/bin/cmake.exe"
config.host_cmake_generator = "Ninja"
config.llvm_use_linker = ""
config.llvm_use_sanitizer = ""
config.host_arch = "AMD64"
config.mlir_src_root = "C:/Users/Yasho/LoopHole/Polygeist/llvm-project/mlir"
config.mlir_obj_root = "C:/Users/Yasho/LoopHole/build/tools/mlir"
config.mlir_tools_dir = "C:/Users/Yasho/LoopHole/build/./bin"
config.mlir_cmake_dir = "C:/Users/Yasho/LoopHole/build/lib/cmake/mlir"
config.mlir_lib_dir = "C:/Users/Yasho/LoopHole/build/./lib"

config.build_examples = 0
config.run_cuda_tests = 0
config.enable_cuda_runner = 0
config.run_rocm_tests = 0
config.enable_rocm_runner = 0
config.gpu_compilation_format = ""
config.rocm_test_chipset = ""
config.enable_spirv_cpu_runner = 0
config.enable_vulkan_runner = 0
config.enable_bindings_python = 0
config.intel_sde_executable = ""
config.mlir_run_amx_tests = 0
config.mlir_run_arm_sve_tests = 0
# This is a workaround for the fact that LIT's:
#   %if <cond>
# requires <cond> to be in the set of available features. 
# TODO: Update LIT's TestRunner so that this is not required.
if config.mlir_run_arm_sve_tests:
    config.available_features.add("mlir_arm_sve_tests")
config.mlir_run_arm_sme_tests = 0
config.mlir_run_x86vector_tests = 0
config.mlir_run_riscv_vector_tests = ""
config.mlir_run_cuda_tensor_core_tests = 0
config.mlir_run_cuda_sm80_tests = 0
config.mlir_run_cuda_sm80_lt_tests = 0
config.mlir_run_cuda_sm90_tests = 0
config.mlir_include_integration_tests = 0
config.arm_emulator_executable = ""
config.arm_emulator_options = ""
config.arm_emulator_mlir_cpu_runner_executable = ""
config.arm_emulator_lli_executable = ""
config.arm_emulator_utils_lib_dir = ""
config.riscv_vector_emulator_executable = ""
config.riscv_vector_emulator_options = ""
config.riscv_emulator_lli_executable = ""
config.riscv_emulator_utils_lib_dir = ""

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, "C:/Users/Yasho/LoopHole/Polygeist/llvm-project/mlir/test/lit.cfg.py")
